version: '3'

services:

  nodeosd:
    image: unification-node
    container_name: nodeosd
    command: /opt/eosio/bin/nodeosd.sh --delete-all-blocks --max-transaction-time=1000
    hostname: nodeosd
    ports:
    - "8888:8888"
    - "9876:9876"

  keosd:
    image: unification-keosd
    container_name: keosd
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address 0.0.0.0:8889
    hostname: keosd
    ports:
    - "8889:8889"

  haiku-app1:
    image: haiku
    container_name: haiku-app1
    environment:
    - app_name=app1
    - keystore=rIeT7sz1P31ijrs9lNZiQGmOKlUVqf1WBg8ZSW-3JR8=
    ports:
    - "8851:8050"

  haiku-app2:
    image: haiku
    container_name: haiku-app2
    environment:
    - app_name=app2
    - keystore=I0CtE8uvYOj9bOaQjlymmZT8621iidsInry0Nqepaak=
    ports:
    - "8852:8050"

  haiku-app3:
    image: haiku
    container_name: haiku-app3
    environment:
    - app_name=app3
    - keystore=Lah5Kwt9mziZh9A_Xi6RQ_quqwII5Bhvw5MZ8xE03IA=
    ports:
    - "8853:8050"
    volumes:
        - ${HAIKU_ROOT}/data_sources/imageblobs:/data_sources/imageblobs:ro

  ipfs:
    image: ipfs
    container_name: ipfs
    command: ipfs daemon --offline
    ports:
    - "5001:5001"

  systemtest:
    image: systemtest
    container_name: systemtest
    command: python /haiku/test/systemtest.py wait
    depends_on:
      - "nodeosd"
      - "keosd"
      - "haiku-app1"
      - "haiku-app2"
      - "haiku-app3"
      - "ipfs"

  babel:
    image: babel
    container_name: babel
    command: python -c 'import time; time.sleep(6000)'
    depends_on:
      - "systemtest"
