version: '3'

services:
  nodeosd:
    image: unification-node
    command: /opt/eosio/bin/nodeosd.sh --resync
    hostname: nodeosd
    ports:
    - "8888:8888"
    - "9876:9876"
  haiku-app1:
    image: haiku
    environment:
    - app_name=app1
    ports:
    - "8851:8050"
  haiku-app2:
    image: haiku
    environment:
    - app_name=app2
    ports:
    - "8852:8050"
  systemtest:
    image: systemtest
    command: python /haiku/test/systemtest.py wait
